import SlideBar from './components/shared/SlideBar';
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nuto = Nunito_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={nuto.className}>
        <SlideBar/>
        {children}
        </body>
    </html>
  )
}
